name: Publish to NuGet and Visual Studio Marketplace

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "8.0.x"

      - name: Restore dependencies
        run: dotnet restore RoodFluweel.ValueObjects.sln

      - name: Build solution
        run: dotnet build RoodFluweel.ValueObjects.sln --configuration Release --no-restore

      - name: Run tests
        run: dotnet test RoodFluweel.ValueObjects.sln --no-build --configuration Release --verbosity normal

      - name: Pack NuGet package
        run: dotnet pack RoodFluweel.ValueObjects.sln --configuration Release --output ./artifacts

      - name: Publish to NuGet
        env:
          NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
        run: |
          dotnet nuget push ./artifacts/*.nupkg \
            --api-key $NUGET_API_KEY \
            --source https://api.nuget.org/v3/index.json
            --skip-duplicate
